### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by brokiem** [Xenophilicy/CrashTransfer#1]
can u add command for transfering? lov this amazing plugin

**Comment by Xenophilicy** [comment]
Hello @brokiem, 

Are you wanting a command that transfers all players without stopping the server?

**Comment by brokiem** [comment]
no, the command to transfer, when the server stop, plugin will transfer the players with commands like /lobby server, this will support the waterdog proxy :D

sorry for my english

**Comment by Xenophilicy** [comment]
Got it, thank you for the clarification! I'll push an update when I have time :)
